Alpine Compatability: casaos-uninstall
 - Remove bashisms
 - Add helper functions to abstract service control

diff --git a/casaos-uninstall b/casaos-uninstall
--- a/casaos-uninstall
+++ b/casaos-uninstall
@@ -39,7 +39,7 @@ echo '
 
 
 # Not every platform has or needs sudo (https://termux.com/linux.html)
-((EUID)) && sudo_cmd="sudo"
+[ "$(id -u)" -ne 0 ] && sudo_cmd="sudo"
 
 readonly CASA_PATH=/casaOS
 readonly CASA_EXEC=casaos
@@ -60,18 +60,16 @@ readonly CASA_HELPER_PATH=/usr/share/casaos/shell
 
 
 readonly COLOUR_RESET='\e[0m'
-readonly aCOLOUR=(
-    '\e[38;5;154m' # green  	| Lines, bullets and separators
-    '\e[1m'        # Bold white	| Main descriptions
-    '\e[90m'       # Grey		| Credits
-    '\e[91m'       # Red		| Update notifications Alert
-    '\e[33m'       # Yellow		| Emphasis
-)
+readonly COLOUR_GREEN='\e[38;5;154m' # green    	| Lines, bullets and separators
+readonly COLOUR_WHITE='\e[1m'        # Bold white	| Main descriptions
+readonly COLOUR_GREY='\e[90m'        # Grey 		| Credits
+readonly COLOUR_RED='\e[91m'         # Red  		| Update notifications Alert
+readonly COLOUR_YELLOW='\e[33m'      # Yellow		| Emphasis
 
-readonly GREEN_LINE=" ${aCOLOUR[0]}─────────────────────────────────────────────────────$COLOUR_RESET"
-readonly GREEN_BULLET=" ${aCOLOUR[0]}-$COLOUR_RESET"
-readonly GREEN_SEPARATOR="${aCOLOUR[0]}:$COLOUR_RESET"
-readonly PASSED="${aCOLOUR[0]}PASSED$COLOUR_RESET"
+readonly GREEN_LINE=" ${COLOUR_GREEN}─────────────────────────────────────────────────────$COLOUR_RESET"
+readonly GREEN_BULLET=" ${COLOUR_GREEN}-$COLOUR_RESET"
+readonly GREEN_SEPARATOR="${COLOUR_GREEN}:$COLOUR_RESET"
+readonly PASSED="${COLOUR_GREEN}PASSED$COLOUR_RESET"
 
 UNINSTALL_ALL_CONTAINER=false
 REMOVE_IMAGES="none"
@@ -93,23 +91,16 @@ REMOVE_APP_DATA=false
 #######################################
 
 Show() {
-    # OK
-    if (($1 == 0)); then
-        echo -e "${aCOLOUR[2]}[$COLOUR_RESET${aCOLOUR[0]}  OK  $COLOUR_RESET${aCOLOUR[2]}]$COLOUR_RESET $2"
-    # FAILED
-    elif (($1 == 1)); then
-        echo -e "${aCOLOUR[2]}[$COLOUR_RESET${aCOLOUR[3]}FAILED$COLOUR_RESET${aCOLOUR[2]}]$COLOUR_RESET $2"
-    # INFO
-    elif (($1 == 2)); then
-        echo -e "${aCOLOUR[2]}[$COLOUR_RESET${aCOLOUR[0]} INFO $COLOUR_RESET${aCOLOUR[2]}]$COLOUR_RESET $2"
-    # NOTICE
-    elif (($1 == 3)); then
-        echo -e "${aCOLOUR[2]}[$COLOUR_RESET${aCOLOUR[4]}NOTICE$COLOUR_RESET${aCOLOUR[2]}]$COLOUR_RESET $2"
-    fi
+    case $1 in
+        0 ) echo -e "${COLOUR_GREY}[$COLOUR_RESET${COLOUR_GREEN}  OK  $COLOUR_RESET${COLOUR_GREY}]$COLOUR_RESET $2";;  # OK
+        1 ) echo -e "${COLOUR_GREY}[$COLOUR_RESET${COLOUR_RED}FAILED$COLOUR_RESET${COLOUR_GREY}]$COLOUR_RESET $2";;    # FAILED
+        2 ) echo -e "${COLOUR_GREY}[$COLOUR_RESET${COLOUR_GREEN} INFO $COLOUR_RESET${COLOUR_GREY}]$COLOUR_RESET $2";;  # INFO
+        3 ) echo -e "${COLOUR_GREY}[$COLOUR_RESET${COLOUR_YELLOW}NOTICE$COLOUR_RESET${COLOUR_GREY}]$COLOUR_RESET $2";; # NOTICE
+    esac
 }
 
 Warn() {
-    echo -e "${aCOLOUR[3]}$1$COLOUR_RESET"
+    echo -e "${COLOUR_RED}$1$COLOUR_RESET"
 }
 
 trap 'onCtrlC' INT
@@ -119,7 +110,7 @@ onCtrlC() {
 }
 
 Detecting_CasaOS() {
-    if [[ ! -x "$(command -v ${CASA_EXEC})" ]]; then
+    if [ ! -x "$(command -v ${CASA_EXEC})" ]; then
         Show 2 "CasaOS is not detected, exit the script."
         exit 1
     else
@@ -129,10 +120,10 @@ Detecting_CasaOS() {
 
 Unistall_Container() {
     Show 2 "Start deleting containers."
-    if [[ ${UNINSTALL_ALL_CONTAINER} == true && "$(${sudo_cmd} docker ps -aq)" != "" ]]; then
+    if [ "${UNINSTALL_ALL_CONTAINER}" = "true" ] && [ "$(${sudo_cmd} docker ps -aq)" != "" ]; then
         ${sudo_cmd} docker stop $(${sudo_cmd} docker ps -aq)
         ${sudo_cmd} docker rm $(${sudo_cmd} docker ps -aq)
-        if [[ $? -ne 0 ]]; then
+        if [ "$?" -ne 0 ]; then
             Show 1 "Failed to delete all containers."
         else
             Show 0 "Successfully deleted all containers."
@@ -141,18 +132,18 @@ Unistall_Container() {
 }
 
 Remove_Images() {
-    if [[ ${REMOVE_IMAGES} == "all" && "$(${sudo_cmd} docker images -q)" != "" ]]; then
+    if [ "${REMOVE_IMAGES}" = "all" ] && [ "$(${sudo_cmd} docker images -q)" != "" ]; then
         Show 2 "Start deleting all images."
         ${sudo_cmd} docker rmi $(${sudo_cmd} docker images -q)
-        if [[ $? -ne 0 ]]; then
+        if [ "$?" -ne 0 ]; then
             Show 1 "Failed to delete all images."
         else
             Show 0 "Successfully deleted all images."
         fi
-    elif [[ ${REMOVE_IMAGES} == "unuse" && "$(${sudo_cmd} docker images -q)" != "" ]]; then
+    elif [ "${REMOVE_IMAGES}" = "unuse" ] && [ "$(${sudo_cmd} docker images -q)" != "" ]; then
         Show 2 "Start deleting unuse images."
         ${sudo_cmd} docker image prune -af
-        if [[ $? -ne 0 ]]; then
+        if [ "$?" -ne 0 ]; then
             Show 1 "Failed to delete unuse images."
         else
             Show 0 "Successfully deleted all images that are not used by the container."
@@ -160,48 +151,88 @@ Remove_Images() {
     fi
 }
 
+Is_Service_Running() {
+    if [ "$USE_SYSTEMD" = "true" ]; then
+        ${sudo_cmd} systemctl is-active --quiet "${1}.service"
+    else
+        ${sudo_cmd} "/etc/init.d/${1}" --quiet status
+    fi
+}
+
+Start_Service() {
+    if [ "$USE_SYSTEMD" = "true" ]; then
+        ${sudo_cmd} systemctl start "${1}.service"
+    else
+        ${sudo_cmd} rc-service "${1}" start
+    fi
+}
+
+Enable_Service() {
+    if [ "$USE_SYSTEMD" = "true" ]; then
+        ${sudo_cmd} systemctl enable "${1}.service"
+    else
+        ${sudo_cmd} rc-update add "${1}" default
+    fi
+}
+
+Stop_Service() {
+    if [ "$USE_SYSTEMD" = "true" ]; then
+        ${sudo_cmd} systemctl stop "${1}.service"
+    else
+        ${sudo_cmd} rc-service "${1}" stop
+    fi
+}
+
+Disable_Service() {
+    if [ "$USE_SYSTEMD" = "true" ]; then
+        ${sudo_cmd} systemctl disable "${1}.service"
+    else
+        ${sudo_cmd} rc-update del "${1}"
+    fi
+}
+
 Uninstall_Casaos() {
 
     # Stop CasaOS Service
-    if [[ $(systemctl is-active ${CASA_EXEC}) == "active" ]]; then
-        ${sudo_cmd} systemctl stop ${CASA_EXEC}
-        ${sudo_cmd} systemctl disable ${CASA_EXEC}
+    if Is_Service_Running "${CASA_EXEC}"; then
+        Stop_Service "${CASA_EXEC}"
+        Disable_Service "${CASA_EXEC}"
     fi
 
     # Remove Service file
-    if [[ -f ${CASA_SERVICE_USR} ]]; then
+    if [ -f "${CASA_SERVICE_USR}" ]; then
         ${sudo_cmd} rm -rf ${CASA_SERVICE_USR}
     fi
 
-    if [[ -f ${CASA_SERVICE_LIB} ]]; then
+    if [ -f "${CASA_SERVICE_LIB}" ]; then
         ${sudo_cmd} rm -rf ${CASA_SERVICE_LIB}
     fi
 
-    if [[ -f ${CASA_SERVICE_ETC} ]]; then
+    if [ -f "${CASA_SERVICE_ETC}" ]; then
         ${sudo_cmd} rm -rf ${CASA_SERVICE_ETC}
     fi
 
     # Old Casa Files
-    if [[ -d ${CASA_PATH} ]]; then
+    if [ -d "${CASA_PATH}" ]; then
         ${sudo_cmd} rm -rf ${CASA_PATH}
-        if [[ $? -ne 0 ]]; then
+        if [ "$?" -ne 0 ]; then
             Show 1 "Failed to delete CasaOS files."
         else
             Show 0 "Successfully deleted CasaOS files."
         fi
     fi
 
-    if [[ -f ${CASA_ADDON1} ]]; then
+    if [ -f "${CASA_ADDON1}" ]; then
         ${sudo_cmd} rm -rf ${CASA_ADDON1}
     fi
 
-    if [[ -f ${CASA_ADDON2} ]]; then
+    if [ -f "${CASA_ADDON2}" ]; then
         ${sudo_cmd} rm -rf ${CASA_ADDON2}
     fi
 
-    if [[ -f ${CASA_BIN} ]]; then
+    if [ -f "${CASA_BIN}" ]; then
         ${sudo_cmd} rm -rf ${CASA_BIN}
-        if [[ $? -ne 0 ]]; then
+        if [ "$?" -ne 0 ]; then
             Show 1 "Failed to delete CasaOS exec file."
         else
             Show 0 "Successfully deleted CasaOS exec file."
@@ -210,41 +241,41 @@ Uninstall_Casaos() {
 
     # New Casa Files
 
-    if [[ -f ${CASA_CONF_PATH} ]]; then
+    if [ -f "${CASA_CONF_PATH}" ]; then
         ${sudo_cmd} rm -rf ${CASA_CONF_PATH}
     fi
 
-    if [[ -d ${CASA_USER_FILES} ]]; then
+    if [ -d "${CASA_USER_FILES}" ]; then
         ${sudo_cmd} rm -rf ${CASA_USER_FILES}
     fi
 
-    if [[ -d ${CASA_HELPER_PATH} ]]; then
+    if [ -d "${CASA_HELPER_PATH}" ]; then
         ${sudo_cmd} rm -rf ${CASA_HELPER_PATH}
     fi
 
-    if [[ -d ${CASA_LOGS_PATH} ]]; then
+    if [ -d "${CASA_LOGS_PATH}" ]; then
         ${sudo_cmd} rm -rf ${CASA_LOGS_PATH}
     fi
 
-    if [[ -f ${CASA_BIN_NEW} ]]; then
+    if [ -f "${CASA_BIN_NEW}" ]; then
         ${sudo_cmd} rm -rf ${CASA_BIN_NEW}
-        if [[ $? -ne 0 ]]; then
+        if [ "$?" -ne 0 ]; then
             Show 1 "Failed to delete CasaOS exec file."
         else
             Show 0 "Successfully deleted CasaOS exec file."
         fi
     fi
 
-    if [[ ${REMOVE_APP_DATA} = true ]]; then
+    if [ "${REMOVE_APP_DATA}" = "true" ]; then
         $sudo_cmd rm -fr /DATA/AppData
-        if [[ $? -ne 0 ]]; then
+        if [ "$?" -ne 0 ]; then
             Show 1 "Failed to delete AppData."
         else
             Show 0 "Successfully deleted AppData."
         fi
     fi
 
-    if [[ -f ${CASA_UNINSTALL_PATH} ]]; then
+    if [ -f "${CASA_UNINSTALL_PATH}" ]; then
         ${sudo_cmd} rm -rf ${CASA_UNINSTALL_PATH}
     fi
 
@@ -255,7 +286,7 @@ Uninstall_Casaos() {
 Detecting_CasaOS
 
 while true; do
-    echo -n -e "         ${aCOLOUR[4]}Do you want delete all containers? Y/n :${COLOUR_RESET}"
+    echo -n -e "         ${COLOUR_YELLOW}Do you want delete all containers? Y/n :${COLOUR_RESET}"
     read input
     case $input in
     [yY][eE][sS] | [yY])
@@ -272,9 +303,9 @@ while true; do
     esac
 done
 
-if [[ ${UNINSTALL_ALL_CONTAINER} == true ]]; then
+if [ "${UNINSTALL_ALL_CONTAINER}" = "true" ]; then
     while true; do
-        echo -n -e "         ${aCOLOUR[4]}Do you want delete all images? Y/n :${COLOUR_RESET}"
+        echo -n -e "         ${COLOUR_YELLOW}Do you want delete all images? Y/n :${COLOUR_RESET}"
         read input
         case $input in
         [yY][eE][sS] | [yY])
@@ -292,7 +323,7 @@ if [[ ${UNINSTALL_ALL_CONTAINER} == true ]]; then
     done
 
     while true; do
-        echo -n -e "         ${aCOLOUR[4]}Do you want delete all AppData of CasaOS? Y/n :${COLOUR_RESET}"
+        echo -n -e "         ${COLOUR_YELLOW}Do you want delete all AppData of CasaOS? Y/n :${COLOUR_RESET}"
         read input
         case $input in
         [yY][eE][sS] | [yY])
@@ -310,7 +341,7 @@ if [[ ${UNINSTALL_ALL_CONTAINER} == true ]]; then
     done
 else
     while true; do
-        echo -n -e "         ${aCOLOUR[4]}Do you want to delete all images that are not used by the container? Y/n :${COLOUR_RESET}"
+        echo -n -e "         ${COLOUR_YELLOW}Do you want to delete all images that are not used by the container? Y/n :${COLOUR_RESET}"
         read input
         case $input in
         [yY][eE][sS] | [yY])
